#@!out=/etc/auros/bootloader.cfg mode=0644
# Generated by aurora — syslinux/isolinux theming fragment. The ISO
# builder splices this into the boot config so even the bootloader
# picks up the active theme.
MENU TITLE @brand_text@
MENU COLOR title        * #FF@accent|hex@ #00000000 none
MENU COLOR border       * #00000000 #00000000 none
MENU COLOR sel          * #FF@accent|on|hex@ #FF@accent|hex@ all
MENU COLOR unsel        * #FF@fg|hex@ #00000000 none
MENU COLOR hotkey       * #FF@accent_warm|hex@ #00000000 none
MENU COLOR hotsel       * #FF@accent|on|hex@ #FF@accent|hex@ all
MENU COLOR help         * #FF@subtle|hex@ #00000000 none
MENU COLOR timeout      * #FF@muted|hex@ #00000000 none
MENU COLOR timeout_msg  * #FF@subtle|hex@ #00000000 none
MENU COLOR disabled     * #FF@muted|hex@ #00000000 none
MENU COLOR scrollbar    * #FF@overlay|hex@ #00000000 none
MENU VSHIFT 6
MENU HSHIFT 4
MENU WIDTH 68
MENU MARGIN 8
MENU ROWS 4
MENU TABMSGROW 12
MENU CMDLINEROW 14
MENU HELPMSGROW 16
